- name: Set Prompt
  ansible.builtin.shell: set-prompt {{ tool_name }}

- name: Copy Elastic repo file
  ansible.builtin.copy:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install ELK
  ansible.builtin.dnf:
    name:
      - elasticsearch
      - kibana
      - logstash
    state: installed

- name: Start ELK
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
  loop:
    - elasticsearch
    - kibana
    - logstash




